### ISSUE TITLE
Mina > 1.0 + other changes

### ISSUE THREAD

**Issue by anulman** [hbin/mina-nginx#3]
Hi @hbin — needed to implement nginx in mina for a project I'm working on and stumbled on your repo. I like your work; it was minimal, flexible, and easy to read.

Made a couple changes while dealing with plugin issues to further satisfy our flow. Will be publishing them shortly; let me know if you'd like a PR back into the project. TL;DR:

- Added `nginx:install` task, which copies the template to the user's repo's `lib/mina/templates` dir;
- Added flexible defaults to the template, e.g. having `server_name` fall back to `domain` if not set;
- Rm'ed `:parse` & `:link` tasks in favor of a comprehensive install in `:setup`
- Added `:print` task, to satisfy the preview functions `parse` was helpful for (runs locally)
- Updated the README with details, obvs

Lmk if a PR makes sense? Also, any thoughts on `:install` vs. `:init` for the new task name?

**Comment by hbin** [comment]
Hi @anulman, thanks for your message, I'd be glad that this repo is useful to you.  All PRs are welcome for this repo, and then I will review the changes and decide to merge it or not.

Per to your changes note, they are all make sense for me. For the task name, the `:install` is better for me
